added pagination, sorting and swagger to my project
Nazar090/online-book-store pull request #4
Opened 2024-08-07 16:57 UTC by Nazar090

2024-08-09 07:47 UTC, Elena-Bruyako requested changes

2024-08-09 07:47 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/controller/BookController.java
> +    // I added pagination, sorting and swagger(but I did it before finishing previous task)
Where are Swagger annotations?

2024-08-10 16:50 UTC, Elena-Bruyako approved these changes

2024-08-16 21:16 UTC, Elena-Bruyako requested changes
see pr

2024-08-16 21:16 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/controller/AuthController.java
> +@RequestMapping("/auth")
swagger annotations are missing

2024-08-16 21:16 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/controller/AuthController.java
> +    public UserResponseDto registerUser(@RequestBody UserRegistrationRequestDto requestDto)
```suggestion
    public UserResponseDto registerUser(@RequestBody @Valid UserRegistrationRequestDto requestDto)
```

2024-08-16 21:16 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/model/User.java
> +    @Column(nullable = false)
```suggestion
    @Column(nullable = false, unique = true)
```

2024-08-16 21:16 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/model/User.java
> +    @Column(name = "first_name", nullable = false)
```suggestion
    @Column(nullable = false)
```

2024-08-16 21:16 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/model/User.java
> +    @Column(name = "last_name", nullable = false)
```suggestion
    @Column(nullable = false)
```

2024-08-16 21:16 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/model/User.java
> +    @JsonProperty("first_name")
```suggestion
```

2024-08-16 21:16 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/model/User.java
> +    @JsonProperty("last_name")
```suggestion
```

2024-08-16 21:16 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/model/User.java
> +    @Column(name = "shipping_address", nullable = false)
```suggestion
```

2024-08-16 21:16 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/service/UserServiceImpl.java
> +        if (userRepository.findByEmail(requestDto.getEmail()).isPresent()) {
```suggestion
        if (userRepository.existsByEmail(requestDto.getEmail())) {
```

2024-08-16 21:16 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/service/UserServiceImpl.java
> +        user.setEmail(requestDto.getEmail());
use mapper

2024-08-16 21:16 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/service/UserServiceImpl.java
> +            throw new RegistrationException("Can't register user");
wrong message, user already exists

2024-08-16 21:16 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/service/UserServiceImpl.java
> +        return userMapper.toDo(savedUser);
```suggestion
        userRepository.save(user);
        return userMapper.toDo(user);
```

2024-08-20 06:42 UTC, Elena-Bruyako requested changes
see comment

2024-08-20 06:42 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/model/User.java
> +    @JsonProperty("first_name")
Why do you need JsonProperty annotation?

2024-08-21 11:00 UTC, okuzan approved these changes

2024-08-21 11:00 UTC, okuzan commented on src/main/java/com/example/onlinebookstore/model/User.java
> +@SQLRestriction(value = "is_deleted=false")
```suggestion
@SQLDelete(sql = "UPDATE employees SET is_deleted = TRUE WHERE id = ?")
@SQLRestriction(value = "is_deleted = FALSE")
```

2024-09-05 13:09 UTC, merged