added JWT support
Nazar090/online-book-store pull request #6
Opened 2024-09-14 22:54 UTC by Nazar090

2024-09-15 17:54 UTC, Elena-Bruyako requested changes
build failed, please fix it first

2024-09-16 10:23 UTC, MentorMateAcademy requested changes

2024-09-16 10:23 UTC, MentorMateAcademy commented on src/main/java/com/example/onlinebookstore/config/OpenApiConfig.java
> +            .addSecurityItem(new SecurityRequirement().addList("BearerAuth"));
Save strings to constants

2024-09-16 10:23 UTC, MentorMateAcademy commented on src/main/java/com/example/onlinebookstore/security/JwtAuthenticationFilter.java
> +        if (StringUtils.hasText(bearerToken) && bearerToken.startsWith("Bearer ")) {
Constants

2024-09-17 16:59 UTC, Elena-Bruyako requested changes
see comments

2024-09-17 16:59 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/controller/AuthController.java
> +    public UserLoginResponseDto login(@RequestBody UserLoginRequestDto request) {
```suggestion
    public UserLoginResponseDto login(@RequestBody @Valid UserLoginRequestDto request) {
```

2024-09-17 16:59 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/config/SecurityConfig.java
> +                            .requestMatchers("/auth/login", "/auth/register",
```suggestion
                            .requestMatchers("/auth/**",
```

2024-09-17 16:59 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/dto/user/UserLoginRequestDto.java
> +        @NotEmpty
```suggestion
        @NotBlank
```

2024-09-17 16:59 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/dto/user/UserLoginRequestDto.java
> +        @NotEmpty
```suggestion
        @NotBlank
```

2024-09-17 16:59 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/security/JwtAuthenticationFilter.java
> +    private static final String authCredentials = "Authorization";
```suggestion
```

2024-09-17 16:59 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/security/JwtAuthenticationFilter.java
> +        String bearerToken = request.getHeader(authCredentials);
```suggestion
        String bearerToken = request.getHeader(HttpHeaders.AUTHORIZATION);
```

2024-09-17 16:59 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/security/JwtAuthenticationFilter.java
> +    private static final String tokenStartsWith = "Bearer ";
```suggestion
    private static final String TOKEN_HEADER = "Bearer ";
```

constants should contain only upper case letters

2024-09-17 16:59 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/security/JwtAuthenticationFilter.java
> +            return bearerToken.substring(7);
```suggestion
            return bearerToken.substring(TOKEN_HEADER.length());
```

2024-09-18 13:30 UTC, Elena-Bruyako requested changes
just one comment

2024-09-18 13:30 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/security/JwtAuthenticationFilter.java
> +        String bearerToken = request.getHeader(AUTHORIZATION);
```suggestion
        String bearerToken = request.getHeader(HttpHeaders.AUTHORIZATION);
```

use Spring constants from import org.springframework.http.HttpHeaders;

2024-09-18 13:30 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/security/JwtAuthenticationFilter.java
> +    private static final String AUTHORIZATION = "Authorization";
```suggestion
```

2024-09-18 21:44 UTC, sarakhmen approved these changes

2024-09-19 08:09 UTC, merged