Add ShoppingCart logic
Nazar090/online-book-store pull request #8
Opened 2024-10-05 13:25 UTC by Nazar090

2024-10-06 11:31 UTC, Elena-Bruyako requested changes
see comments

2024-10-06 11:31 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/controller/ShoppingCartController.java
> +    public CartItemResponseDto addCartItem(
```suggestion
    public ShoppingCartResponseDto addCartItem(
```

2024-10-06 11:31 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/controller/ShoppingCartController.java
> +    public CartItemResponseDto updateCartItem(@PathVariable Long cartItemId,
```suggestion
    public ShoppingCartResponseDto updateCartItem(@PathVariable Long cartItemId,
```

2024-10-06 11:31 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/controller/ShoppingCartController.java
> +            return authentication.getName();
it's better to return userId because it's index and increase searching by userId in DB

2024-10-06 11:31 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/dto/cartitem/CartItemRequestDto.java
> +    private Long bookId;
```suggestion
    @NotNull
    @Positive
    private Long bookId;
```

2024-10-06 11:31 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/dto/cartitem/CartItemRequestDto.java
> +    @Min(1)
```suggestion
    @Positive
```

2024-10-06 11:31 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/dto/cartitem/CartItemQuantityDto.java
> +    @Min(1)
```suggestion
    @Positive
```

2024-10-06 11:31 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/dto/shoppingcart/ShoppingCartRequestDto.java
> +public class ShoppingCartRequestDto {
unused dto, remove it

2024-10-06 11:31 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/model/CartItem.java
> +@Entity
add Table annotation

2024-10-06 11:31 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/model/ShoppingCart.java
> +@Entity
same here

2024-10-06 11:31 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/model/ShoppingCart.java
> +    @JoinColumn(name = "user_id", nullable = false)
```suggestion
    @MapsId
    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id", nullable = false)
```

2024-10-06 11:31 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/model/ShoppingCart.java
> +    @OneToMany(mappedBy = "shoppingCart")
```suggestion
    @OneToMany(mappedBy = "shoppingCart", cascade = CascadeType.ALL, orphanRemoval = true)
```

2024-10-06 11:31 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/model/ShoppingCart.java
> +    private Set<CartItem> cartItems;
```suggestion
    private Set<CartItem> cartItems = new HashSet<>();
```

2024-10-06 11:31 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/model/ShoppingCart.java
> +    @Getter
```suggestion
```

2024-10-06 11:31 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/model/ShoppingCart.java
> +    @Column(name = "is_deleted")
```suggestion
```

2024-10-06 11:31 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/repository/ShoppingCartRepository.java
> +
```suggestion
    @EntityGraph(attributePaths = {"cartItems", "cartItems.book"})
    ShoppingCart findByUserId(Long userId);
```

2024-10-06 11:31 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/service/ShoppingCartService.java
> +    CartItemResponseDto addCartItem(String email, CartItemRequestDto cartItemRequestDto);
```suggestion
    ShoppingCartResponseDto addCartItem(String email, CartItemRequestDto cartItemRequestDto);
```

2024-10-06 11:31 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/service/ShoppingCartService.java
> +    CartItemResponseDto updateBookQuantity(Long cartItemId,
```suggestion
    ShoppingCartResponseDto updateBookQuantity(Long cartItemId,
```

2024-10-06 11:31 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/service/impl/ShoppingCartServiceImpl.java
> +        User user = getUserByEmail(email);
redundant query to DB
see the comment in Controller and provide userId everywhere

2024-10-06 11:31 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/service/impl/ShoppingCartServiceImpl.java
> +                .orElseGet(() -> registerNewShoppingCart(user));
it's better to create shop cart when user registers.

2024-10-06 11:31 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/service/impl/ShoppingCartServiceImpl.java
> +    @Override
think where Transactional annotation is needed

2024-10-06 11:31 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/service/impl/ShoppingCartServiceImpl.java
> +        CartItem cartItem = cartItemRepository.findById(cartItemId)
```suggestion
        ShoppingCart cart = repository.findByUserId(userId);
        CartItem cartItem = itemRepository.findByIdAndShoppingCartId(cartItemId, cart.getId())
                .map(item -> {
                    item.setQuantity(itemDto.quantity());
                    return item;
                }).orElseThrow(() -> new EntityNotFoundException(
                        String.format("No cart item with id: %d for user: %d", cartItemId, userId)
                ));
```

2024-10-06 11:31 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/service/impl/ShoppingCartServiceImpl.java
> +    private ShoppingCart registerNewShoppingCart(User user) {
```suggestion
    public ShoppingCart registerNewShoppingCart(User user) {
```

call this method in register user method

2024-10-06 11:31 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/10-create-shopping-cart-table.yaml
> +            tableName: shopping_cart
```suggestion
            tableName: shopping_carts
```

2024-10-06 11:31 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/11-create-cart-item-table.yaml
> +            tableName: cart_item
```suggestion
            tableName: cart_items
```

2024-10-07 12:35 UTC, Elena-Bruyako requested changes
see comments

2024-10-07 12:35 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/service/impl/ShoppingCartServiceImpl.java
> +        ShoppingCart shoppingCart = shoppingCartRepository.findByUserId(user.getId());
```suggestion
        ShoppingCart shoppingCart = shoppingCartRepository.findByUserId(userId);
```

you provide userId from endpoint to service

2024-10-07 12:35 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/service/impl/ShoppingCartServiceImpl.java
> +        ShoppingCart shoppingCart = shoppingCartRepository.findByUserId(user.getId());
```suggestion
        ShoppingCart shoppingCart = shoppingCartRepository.findByUserId(userId);
```

2024-10-07 12:35 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/service/impl/ShoppingCartServiceImpl.java
> +        CartItem cartItem = cartItemRepository.findById(cartItemId)
fix comment

2024-10-07 12:35 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/service/impl/ShoppingCartServiceImpl.java
> +    private User getUserById(Long userId) {
remove

2024-10-07 12:35 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/service/impl/ShoppingCartServiceImpl.java
> +    public void registerNewShoppingCart(User user) {
```suggestion
    @Override
    public void registerNewShoppingCart(User user) {
```

2024-10-07 12:35 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/service/impl/ShoppingCartServiceImpl.java
> +    public void registerNewShoppingCart(User user) {
replace before private methods

2024-10-08 06:57 UTC, liliia-ponomarenko requested changes
Good job! But one previous comment remains uncorrected. Let's fix it ;)

2024-10-08 06:57 UTC, liliia-ponomarenko commented on src/main/java/com/example/onlinebookstore/service/impl/ShoppingCartServiceImpl.java
> +        CartItem cartItem = cartItemRepository.findById(cartItemId)
not fixed

2024-10-08 06:57 UTC, liliia-ponomarenko commented on src/main/java/com/example/onlinebookstore/repository/ShoppingCartRepository.java
> +
```suggestion
```

2024-10-08 06:57 UTC, liliia-ponomarenko commented on src/main/java/com/example/onlinebookstore/model/CartItem.java
> +    @ManyToOne(optional = false)
Use fetch type LAZY

2024-10-08 13:08 UTC, Elena-Bruyako requested changes
one comment

2024-10-08 13:08 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/model/CartItem.java
> +    @ManyToOne(optional = false)
```suggestion
    @ManyToOne(optional = false, fetch = FetchType.LAZY)
```

2024-10-09 08:49 UTC, ahoienko approved these changes
Good job!

2024-10-13 11:59 UTC, merged